CREATE DATABASE IF NOT EXISTS hall_of_luck DEFAULT CHARACTER SET utf8mb4;
USE hall_of_luck;

CREATE USER IF NOT EXISTS 'game_admin'@'localhost' IDENTIFIED BY '1234';

GRANT ALL PRIVILEGES ON hall_of_luck.* TO 'game_admin'@'localhost';
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nickname VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS gacha_results (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    item_name VARCHAR(100) NOT NULL,
    rank_grade VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS stats (
    user_id INT PRIMARY KEY,
    total_pulls INT DEFAULT 0,
    highest_rank VARCHAR(10) DEFAULT 'None',
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE gacha_results;
TRUNCATE TABLE stats;
TRUNCATE TABLE users;

SET FOREIGN_KEY_CHECKS = 1;